baseURL = 'https://showa44man.com/'
locale = 'en-us'
title = '昭和44年男'
theme = 'PaperMod'
buildFuture = true

[params]
  favicon = "/favicon.ico"

[[menus.main]]
  name = "プロフィール"
  url = "/about/"
  weight = 10

[[menus.main]]
  name = "お問い合わせ"
  url = "/contact/"
  weight = 20

[[menus.main]]
  name = "プライバシーポリシー"
  url = "/privacy/"
  weight = 30
